'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ListeMedicaments
    
    '''<summary>
    '''rlv_part control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rlv_part As Global.System.Web.UI.WebControls.ListView
    
    '''<summary>
    '''txt_nom_mairie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nom_mairie As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_ville control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ville As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddl_commune control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_commune As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txt_adresse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_adresse As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_longitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_longitude As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_latitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_latitude As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_description As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadBtn_Save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBtn_Save As Global.System.Web.UI.WebControls.Button
End Class
